name: Auto Approve PR

permissions:
  pull-requests: write
  contents: read

on: [pull_request_target]

jobs:
  auto-approve:
    if: github.repository_owner == 'MicrosoftDocs'
    uses: MicrosoftDocs/defender-docs/.github/workflows/MSecD-Shared-AutoApprove.yml@workflows-test
    secrets: inherit
